# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Cryptid.destroy_all
Expedition.destroy_all
Sighting.destroy_all

puts "Assets Destroyed"


20.times {User.create(name: Faker::Books::Dune.unique.character, years_experience: rand(0..30), password: "sdfibdsaf")}
puts "20 Users created"

Cryptid.create(name: "Ozark Howler", description: "A legendary creature that is purported to live in remote areas in Arkansas, Missouri, Oklahoma, and Texas. It is typically described as being bear sized, with a thick body, stocky legs, black shaggy hair, glowing red eyes, and prominent horns. Its cry is often described as being a combination of a wolf's howl, an elk's bugle, and the laugh of a hyena.")
# Cryptid.create(name: "Fouke Monster", description: Faker::Lorem.paragraph)
Cryptid.create(name: "Almas", description: "An ape-like cryptid reported from Central Asia. They are said to inhabit the Asian mountain regions of Pamir and Caucasus as well as the Mongolian mountain range Altai. Sightings of the Almas date back as early as the 15th century.")
Cryptid.create(name: "Yowie", description: "A fanged humanoid marsupial or great ape, featured in Aboriginal mythology along with Australian Raptors, Bunyips and Burrunjor. The Yowie is considered to be the Australian Bigfoot, and contain many primate like features, possibly indicating that it is an undiscovered species of great ape (Gigantopithecus) or prehistoric human. The Yowie is described as being one of the most aggressive Sasquatch species, and has been reported tearing heads off of kangaroos and dogs. It has been seen attacking humans as well. However, that is rare.")
Cryptid.create(name: "Yeren", description: "A mysterious primate living in the mountains of China, with most of the sightings coming from the remote Hubei province. It has reddish brown hair and a large jaw. It is six to eight feet tall, and is generally friendly but reserved around humans. Many footprints and hair traces have been found. Despite its size, it is said to be less robust and stocky than its other relatives like Sasquatch.")
Cryptid.create(name: "Ebu Gogo", description: "A humanoid creature that appears in Nage Mythology. The Nage people of Flores, Indonesia describe the Ebu Gogo as having been able walkers and fast runners around 1.5m tall. They reportedly had wide and flat noses, broad faces with large mouths and hairy bodies. The females also had 'long, pendulous breasts'. They were said to have murmured in what was assumed to be their own language and could reportedly repeat what was said to them in a parrot-like fashion. The Nage people believe that the Ebu Gogo were alive at the time of the arrival of Portuguese Trading Ship in the 17th century, and some hold that they survived as recently as the 20th century, but are now no longer seen.")
Cryptid.create(name: "Skunk Ape", description: "A bipedal humanoid, possibly a Bigfoot, reported in the South Eastern United States including Texas, Georgia, and Louisiana, but most notably in the Florida Everglades. It has black fur and glowing red eyes, unusual for most primates because most primates lack a tapetum lucidum, a layer of tissue behind the retina that reflects light. The Skunk Ape's most obvious character is its terrible odor, which gives it its name.")
Cryptid.create(name: "Mongolian Death Worm", description: "The Mongolian Death Worm's native name, Olgoi-Khorkhoi, means ‘intestine worm’, due to its red blood-like color, and size, which is the size of an intestine. It has been described by many to be from 2-7ft long, have the ability to spit out a corrosive yellow saliva and to generate blasts of electricity. However this latter power is thought of as being folkloric by the nomads of the Gobi. Western culture has come to call this monster the ‘Mongolian Death Worm.’")
Cryptid.create(name: "Yeti", description: "In Buddhist mythology, the Yetis were peaceful creatures, that were very shy, and lived in dense snow caves on the glaciers which form the Ganges River in India. In modern times, most sightings and evidence are on K2. The name Yeti derives from ‘Yeh-Tah’, meaning ‘rock thing’. The Yeti was even mentioned in pre-Buddhist cultures, such as the Lecha people, who worshiped a ‘Glacier Giant.’ Tibetan and Nepalese monasteries have collected several skulls and bones of the yetis, some which preside in the Smithsonian Museum today. Although one of their specimens was proven to be a human bone, others contained the museum are still in question.")
Cryptid.create(name: "Honey Island Swamp Monster", description: "The Honey Island Swamp Monster is a humanoid cryptid that is reported to have been seen in and around Honey Island Swamp, Louisiana since 1963. It was first reported in 1963, when two hunters spotted this creature prowling the swamps. Its tracks indicate three-toed webbed feet. It is possible that a Bigfoot evolved webbed feet to better suit its swamp environment. Some even believe it's an experiment gone awry.")
Cryptid.create(name: "Barmanou", description: "The Barmanou is the Pakistani equivalent of the Bigfoot. The term Barmanou is used in several Pakistani languages including Khowar, Shina, Hindko and Kashmiri. In addition to the name Barmanou, there are other local names as well.")
Cryptid.create(name: "Monkey-Man of Delhi", description: "The Monkey Man of New Delhi was an ape like creature that terrorized the capital city of New Delhi, India in 2001. In May of that year, stories began to circulate in New Delhi of a strange, nocturnal, monkey-like creature that was attacking people. Eyewitness accounts were often inconsistent, but tended to describe the creature as about four feet tall, covered in thick black hair. It supposedly wore a metal helmet, had metal claws, pants, glowing red eyes, sometimes beneath goggles, and three buttons on its chest. Some suggest the Monkey Man is an avatar of the Hindu deity Hanuman, while others claim it is a version of Bigfoot.")
Cryptid.create(name: "Chupacabra", description: "El Chupacabra is a cryptid that is renowned for its attacks on livestock, hence the Spanish name ‘the goatsucker.’ It supposedly eats chickens, goats, and other farm animals and pets. It has been reported all over the Americas, specifically the Southwestern United States, Mexico and Puerto Rico. There are two common versions of the chupacabra. There is a reptilian kind - the true chupacabra - and a canid kind, which are also called blue dogs. There have been more than 2,000 sightings of both types.  When it sucks blood, it allegedly makes an odd noise.")
Cryptid.create(name: "Chuchunya", description: "hominid cryptid reported to exist in Siberia, and described by most eyewitnesses as being a tall (6-7ft) and human-like, with broad shoulders, a large protruding brow, long, matted hair and occasionally bearing unusual fur coloration, this creature also seen use cloth from animal skins. some researchers to believe that these creatures may have less in common with Gigantopithecus-like creatures such as Bigfoot or the Yeti, and may possibly be a part of what some have speculated are a relic population of paleo-asiatic aborigines or possibly even Neanderthals.")
Cryptid.create(name: "Lizard Man of Scape Ore Swamp", description: "Many theories have been presented in relation to the identity of Lizard Men, theories such as living dinosaurs, and even offshoots of evolution in which the reptilian hierarchy continued to evolve along the same path as early primates. At one point in time reptiles ruled the earth, it is not out of the realm of possibility that the most dominate species on the planet could continue to evolve in small numbers unseen by mankind. Although no reptilian species known to man have shown signs of such advanced evolution, the reptile is the oldest and most successful species on the planet and could hold secrets that have yet to come to light. In Lee County, South Carolina, a strange reptilian humanoid was reported on several accounts.")
Cryptid.create(name: "Mothman", description: "Mothman is described as a bipedal, winged humanoid. Despite his name which was given to him by newspapers, he is in no way moth-like, and has an appearance more like that of a large humanoid owl. His coloration varies from Black, gray, to even brown, although its is usually the darker shades. He is often reported to be about 7 feet tall, with a wingspan of about 10 to 15 feet or more, plus the ability to fly over 100 mph. Sometimes hes described as not having a head with the two huge red eyes set in the chest. These eyes are reported to be glowing, or at least reflective. The details of his face and his feet have never been adequately described. One witness who saw the face clearly, could only say that the details were horrible and monstrous. She had terrible nightmares and nearly suffered a nervous breakdown.")
Cryptid.create(name: "Jersey Devil", description: "The Jersey Devil is a creature native to the Pine Barrens of New Jersey. It is often described as having hooves, a snake's tail, bat-wings and a head that looks something like a horse. While there are many stories detailing the origin of the Jersey Devil, sightings have been reported beginning in the 1700s and continuing on until the past decade. The creature is deeply rooted in folklore and legend in the area, and is still mildly popular in various media, from sports teams to video games.")
Cryptid.create(name: "Loch Ness Monster", description: "Witnesses tend to describe an animal with sleek, rubbery blackish-gray skin, about twenty feet long. Nessie usually has the serpentine body that is typical for sea serpents and lake monsters, furnished with humps along its length, and one or more sets of paddles (or sometimes, stumpy legs). Nessie's head is often described as roughly horse-shaped, it may have a straggly mane running down its neck, and some witnesses report small horns or a crest, especially those who see the Loch Ness monster from close up. Sometimes, witnesses report a smaller, rounded, turtle-like head. This head is the one that seems to appear in most of the famous Nessie photos.")
Cryptid.create(name: "Kraken", description: "The Kraken is a colossal legendary sea monster said to dwell off the coasts of Norway and Greenland. In 2012, scientists discovered a giant squid that corresponded to the physical description of the Kraken, using deep sea exploration with special lighting displays designed to attract large predators. The sheer size and fearsome appearance attributed to the Kraken have made it a common ocean-dwelling monster in various fictional works. Kraken is also one of the most (if not the most) largest cryptids that may have ever existed, and is so far the only thing in the Massive category.")
Cryptid.create(name: "Ogopogo", description: "The most common description of Ogopogo is a 40-50 foot long (12 to 15 m) sea serpent. British cryptozoologist Karl Shuker has categorized the Ogopogo as a 'many hump' variety of lake monster, and suggested it may be a kind of primitive serpentine whale such as Basilosaurus, that lived 40 million years ago. However, because the physical evidence for the beast is limited to unclear photographs and film, it has also been suggested that the sightings are misidentifications of common animals, such as otters, and inanimate objects such as floating logs. It's also possible that it's a plesiosaur, mosasaur or pliosaur. There is a myth that in the middle of the lake, there is a cave, and thats where the Ogopogo lives.")
Cryptid.create(name: "Selma", description: "Selma is a lake monster situated near Telemark, Norway, in Lake Seljordsvatnet, a twelve mile long and one and a half mile wide body of icy cold water formed by glaciers during the last ice age. As far back as the late 1750s reports of a large reptilian creature living in the lake have circulated around the region. Eyewitness reports, which today number over 500, generally describe the creature, dubbed Selma by the locals, as a 30 to 45 foot serpent like creature, resembling a large anaconda; some reports even include several humps on its back.")
# Cryptid.create(name: "Tahoe Tessie", description: Faker::Lorem.paragraph)
bigfoot = Cryptid.create(name: "Sasquatch", description: "The Sasquatch is a type of Bigfoot said to inhabit areas of North America. The term Sasquatch was first used in 1920 by British Columbian school teacher J.W. Burns. It is an anglicized version of the Halkomelem word sásq'ets, which translates to ‘wild man’. Stories of an ape like creature roaming the forests of North America have been around as long as some of the Native Americans tribes started in certain areas, due to the finding of cave painting of Sasquatches. However, the earliest written account was made in 1811 by David Thompson, who was mapping regions of Canada and the United States of America during the time.")
puts "22 Cryptids Created"

seasons = ["Spring", "Summer", "Fall", "Winter"]
regions = ["Pacific Northwest", "Southwest", "Midwest", "Northeast", "Southeast"] 
60.times {Expedition.create(days: rand(1..15), season: seasons.sample, region: regions.sample, user_id: User.all.sample.id, name: Faker::Kpop.unique.boy_bands)}
puts "60 Expeditions Created"

temperament = ["Confident", "Shy", "Independent", "Happy", "Aggressive", "Curious"]
60.times {Sighting.create(
        date: Faker::Date.between(from: '2002-01-23', to: '2020-11-29'), 
        location: Faker::Mountain.name, 
        creature_temperament: temperament.sample, 
        fear_rating: rand(1..10), 
        description: Faker::Lorem.paragraph, 
        expedition_id: Expedition.all.sample.id, 
        user_id: User.all.sample.id, 
        cryptid_id: Cryptid.all.sample.id)}


40.times {Sighting.create(
        date: Faker::Date.between(from: '2002-01-23', to: '2020-11-29'), 
        location: Faker::Mountain.name, 
        creature_temperament: temperament.sample, 
        fear_rating: rand(1..10), 
        description: Faker::Lorem.paragraph, 
        expedition_id: Expedition.all.sample.id, 
        user_id: User.all.sample.id, 
        cryptid_id: bigfoot.id)}

puts "Sightings Created"
